import Iconify from '../components/iconify';
import LocationStarIcon from '@iconify/icons-carbon/location-star';
import AreaCustomIcon from '@iconify/icons-carbon/area-custom';
import ArchitectureIcon from '@iconify/icons-mdi/architecture';
import ArchitectIcon from '@iconify/icons-material-symbols/architecture';
import ChairOutlineIcon from '@iconify/icons-material-symbols/chair-outline';
import GrassIcon from '@iconify/icons-material-symbols/grass';
import HomeModernIcon from '@iconify/icons-heroicons/home-modern';
import PersonIcon from '@iconify/icons-carbon/person';
import CameraIcon from '@iconify/icons-carbon/camera';
import StarIcon from '@iconify/icons-carbon/star';
import MapOutlineIcon from '@iconify/icons-ion/map-outline';
import BookmarkIcon from '@iconify/icons-carbon/bookmark';
import ArchitectureHuiStyleIcon from '@iconify/icons-tdesign/architecture-hui-style';
import QuoteIcon from '@iconify/icons-icon-park-outline/quote';

export const _breadcrumbsDMH = {
  '/dallas-modern-homes/': {
    name: 'Dallas Modern Homes',
    icon: <Iconify icon={HomeModernIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/dallas-modern-homes/',
    parent: false,
    dropdown: [
      '/modern/',
      '/texas-modern/',
      '/mid-century/',
      '/for-sale/',
      '/modern-in-mls/',
    ],
  },
  '/modern/': {
    name: 'Modern',
    href: '/dallas-modern-homes/modern/',
    parent: '/dallas-modern-homes/',
  },
  '/texas-modern/': {
    name: 'Texas Modern',
    href: '/dallas-modern-homes/texas-modern/',
    parent: '/dallas-modern-homes/',
  },
  '/mid-century/': {
    name: 'Mid-Century Modern',
    href: '/dallas-modern-homes/mid-century/',
    parent: '/dallas-modern-homes/',
  },
  '/for-sale/': {
    name: 'Modern Homes for Sale',
    href: '/dallas-modern-homes/for-sale/',
    parent: '/dallas-modern-homes/',
  },
  '/modern-in-mls/': {
    name: 'Modern in MLS',
    href: '/dallas-modern-homes/mls/',
    parent: '/dallas-modern-homes/',
  },
};
export const _breadcrumbs = {
  '/': {
    name: 'Architecturally Significant Homes',
    icon: <Iconify className="flex-shrink-0 w-5 h-5" icon={BookmarkIcon} />,
    href: '/',
    parent: false,
    dropdown: [
      '/featured-listings/',
      '/neighborhoods/',
      '/architecture/',
      '/architects/',
      '/dallas-modern-homes/',
      '/about/',
      '/life-in-dallas/',
      '/architecture-coast-to-coast/',
    ],
  },
  '/featured-listings/': {
    name: 'Featured Listings',
    icon: <Iconify icon={LocationStarIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/featured-listings/',
    parent: '/about/',
  },
  '/architectural-styles/': {
    name: 'Dallas Architectural Styles',
    icon: (
      <Iconify
        icon={ArchitectureHuiStyleIcon}
        className="flex-shrink-0 h-4 w-4"
      />
    ),
    href: '/architecture/architectural-styles/',
    parent: '/architecture/',
    dropdown: [
      '/dallas-modern-architecture/',
      '/texas-modern-architecture/',
      '/dallas-eclectic-architecture/',
    ],
  },
  '/texas-modern-architecture/': {
    name: 'Texas Modern Architecture',
    href: '/architecture/texas-modern-architecture/',
    parent: '/architectural-styles/',
  },
  '/dallas-modern-architecture/': {
    name: 'Dallas Modern Architecture',
    href: '/architecture/dallas-modern-architecture/',
    parent: '/architectural-styles/',
  },
  '/dallas-eclectic-architecture/': {
    name: 'Dallas Eclectic Architecture',
    href: '/architecture/dallas-eclectic-architecture/',
    parent: '/architectural-styles/',
  },
  '/architecturally-significant-homes/': {
    name: 'Architecturally Significant Homes',
    icon: <Iconify icon={StarIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/architecture/architecturally-significant-homes/',
    parent: '/architecture/',
    dropdown: ['/preservation-park-cities-top-100/'],
  },
  '/preservation-park-cities-top-100/': {
    name: 'Preservation Park Cities Top 100',
    href: '/architecture/architecturally-significant-homes/',
    parent: '/architecturally-significant-homes/',
  },
  '/interior-designers/': {
    name: 'Interior Designers',
    icon: <Iconify icon={ChairOutlineIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/architecture/interior-designers/',
    parent: '/architects/',
  },
  '/landscape-architects/': {
    name: 'Landscape Architects',
    icon: <Iconify icon={GrassIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/architecture/landscape-architects/',
    parent: '/architects/',
  },
  '/architecture/': {
    name: 'Architecture',
    icon: <Iconify icon={ArchitectureIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/architecture/',
    parent: '/about/',
    dropdown: [
      '/architects/',
      '/architectural-styles/',
      '/architecturally-significant-homes/',
      '/interior-designers/',
      '/dallas-modern-homes/',
      '/landscape-architects/',
      '/dallas-architecture-quotes/',
    ],
  },
  '/dallas-architecture-quotes/': {
    name: 'Dallas Quotes on Architecture',
    icon: <Iconify icon={QuoteIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/dallas-architecture-quotes/',
    parent: '/architecture/',
  },
  '/architects/': {
    name: 'Architects',
    icon: <Iconify icon={ArchitectIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/architects/',
    parent: '/architecture/',
    dropdown: [
      '/architects-dallas-and-regional/',
      '/architects-international/',
      '/retired-architects-dallas-and-regional/',
      '/retired-architects-international/',
      '/landscape-architects/',
      '/interior-designers/',
    ],
  },
  '/architects-dallas-and-regional/': {
    name: 'Best Dallas Architects',
    icon: <Iconify icon={ArchitectIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/architects-dallas-and-regional/',
    parent: '/architects/',
  },
  '/architects-international/': {
    name: 'International Architects',
    icon: <Iconify icon={ArchitectIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/architects-international/',
    parent: '/architects/',
  },
  '/retired-architects-dallas-and-regional/': {
    name: 'Significant Past Dallas Architects',
    icon: <Iconify icon={ArchitectIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/retired-architects-dallas-and-regional/',
    parent: '/architects/',
  },
  '/retired-architects-international/': {
    name: 'Significant Past International Architects',
    icon: <Iconify icon={ArchitectIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/architecture/retired-architects-international/',
    parent: '/architects/',
  },
  '/dallas-modern-homes/': {
    name: 'Dallas Modern Homes',
    icon: <Iconify icon={HomeModernIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/dallas-modern-homes/',
    parent: '/about/',
    dropdown: [
      '/modern/',
      '/texas-modern/',
      '/mid-century/',
      '/for-sale/',
      '/modern-in-mls/',
    ],
  },
  '/modern/': {
    name: 'Modern',
    href: '/dallas-modern-homes/modern/',
    parent: '/dallas-modern-homes/',
  },
  '/texas-modern/': {
    name: 'Texas Modern',
    href: '/dallas-modern-homes/texas-modern/',
    parent: '/dallas-modern-homes/',
  },
  '/mid-century/': {
    name: 'Mid-Century Modern',
    href: '/dallas-modern-homes/mid-century/',
    parent: '/dallas-modern-homes/',
  },
  '/for-sale/': {
    name: 'Modern Homes for Sale',
    href: '/dallas-modern-homes/for-sale/',
    parent: '/dallas-modern-homes/',
  },
  '/about/': {
    name: 'About Douglas Newby',
    icon: <Iconify icon={PersonIcon} className="flex-shrink-0 h-5 w-5" />,
    href: '/about/',
    parent: '/',
    dropdown: [
      '/appreciation-testimonials/',
      '/articles/',
      '/motivation/',
      '/preservation-accomplishments/',
      '/vision/',
      '/neighborhood-knowledge/',
      '/client-profiles/',
      '/results/',
      '/specializing-architecturally-significant-homes/',
      '/case-studies/',
      '/approach/',
      '/contributions-to-dallas-architecture/',
      '/origins/',
      '/douglas-newby-insights/',
      '/about-the-website/',
    ],
  },
  '/biography-section-of-hinsdale-hall-of-fame-nomination/': {
    href: '/about/biography-section-of-hinsdale-hall-of-fame-nomination/',
    name: 'Hinsdale Hall of Fame Nomination',
    parent: '/about/',
  },
  '/appreciation-testimonials/': {
    href: '/about/appreciation-testimonials/',
    name: 'Appreciation & Testimonials',
    parent: '/about/',
  },
  '/articles/': {
    href: '/articles/',
    name: 'Media & Articles',
    parent: '/about/',
  },
  '/motivation/': {
    href: '/about/motivation/',
    name: 'Motivation of Douglas Newby',
    parent: '/about/',
  },
  '/vision/': {
    href: '/about/vision/',
    name: 'Vision of Douglas Newby',
    parent: '/about/',
  },
  '/neighborhood-knowledge/': {
    href: '/about/neighborhood-knowledge/',
    name: 'Douglas Newby Knows Dallas Neighborhoods',
    parent: '/about/',
  },
  '/client-profiles/': {
    href: '/about/client-profiles/',
    name: 'Profile of Douglas Newby Clients',
    parent: '/about/',
  },
  '/results/': {
    href: '/about/results/',
    name: 'Joy in the Process and Results',
    parent: '/about/',
  },
  '/specializing-architecturally-significant-homes/': {
    href: '/about/specializing-architecturally-significant-homes/',
    name: 'Specializing in Architecturally Significant Homes',
    parent: '/about/',
  },
  '/origins/': {
    href: '/about/origins/',
    name: 'Douglas Newby Origins',
    parent: '/about/',
  },
  '/case-studies/': {
    href: '/about/case-studies/',
    name: 'Case Studies - Success of Clients',
    parent: '/about/',
  },
  '/preservation-accomplishments/': {
    href: '/about/preservation-accomplishments/',
    name: 'Preservation Accomplishments of Douglas Newby',
    parent: '/about/',
  },
  '/approach/': {
    href: '/about/approach/',
    name: 'Douglas Newby Approach',
    parent: '/about/',
  },
  '/contributions-to-dallas-architecture/': {
    href: '/about/contributions-to-dallas-architecture/',
    name: 'Contributions to Dallas Architecture',
    parent: '/about/',
  },
  '/about-the-website/': {
    href: '/about-the-website/',
    name: 'About the Website',
    parent: '/about/',
  },
  '/life-in-dallas/': {
    name: 'Life in Dallas',
    icon: <Iconify icon={CameraIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/life-in-dallas/',
    parent: '/about/',
  },
  '/douglas-newby-insights/': {
    name: 'Douglas Newby Insights',
    href: '/douglas-newby-insights/',
    parent: '/about/',
  },
  '/purchase-architecture/': {
    name: 'Purchase Architecture',
    href: '/architecture-coast-to-coast/purchase-architecture/',
    parent: '/architecture-coast-to-coast/',
  },
  '/architecture-united-states/': {
    name: 'Architecture United States',
    href: '/architecture-coast-to-coast/architecture-united-states/',
    parent: '/architecture-coast-to-coast/',
  },
  '/architecture-regional/': {
    name: 'Architecture Regional',
    href: '/architecture-coast-to-coast/architecture-regional/',
    parent: '/architecture-coast-to-coast/',
  },
  '/architecture-cities/': {
    name: 'Architecture Cities',
    href: '/architecture-coast-to-coast/architecture-cities/',
    parent: '/architecture-coast-to-coast/',
  },
  '/architecture-international/': {
    name: 'Architecture International',
    href: '/architecture-coast-to-coast/architecture-international/',
    parent: '/architecture-coast-to-coast/',
  },
  '/architecture-coast-to-coast/': {
    name: 'Architecture Coast to Coast',
    icon: <Iconify icon={MapOutlineIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/architecture-coast-to-coast/',
    parent: '/about/',
    dropdown: [
      '/architecture-united-states/',
      '/architecture-regional/',
      '/architecture-cities/',
      '/architecture-international/',
      '/purchase-architecture/',
    ],
  },
  '/mls/': {
    name: 'MLS',
    href: '/mls/',
    parent: '/about/',
  },
  '/modern-in-mls/': {
    name: 'Modern in MLS',
    href: '/dallas-modern-homes/mls/',
    parent: '/dallas-modern-homes/',
  },
  '/neighborhoods/': {
    name: 'Neighborhoods',
    icon: <Iconify icon={AreaCustomIcon} className="flex-shrink-0 h-4 w-4" />,
    href: '/neighborhoods/',
    parent: '/about/',
    dropdown: [
      '/highland-park/',
      '/preston-hollow/',
      '/turtle-creek-corridor/',
      '/park-cities/',
      '/university-park/',
      '/bluffview-area/',
      '/greenway-parks/',
      '/munger-place/',
      '/swiss-avenue-historic-district/',
      '/east-dallas/',
      '/white-rock-lake/',
      '/downtown-dallas/',
      '/kessler-park/',
      '/far-north-dallas/',
      '/outside-of-dallas/',
      '/bent-tree/',
      '/glen-abbey/',
      '/northwest-dallas/',
      '/oak-cliff/',
      '/lake-highlands/',
      '/forest-lane-to-lbj/',
      '/merriman-park-university-manor/',
      '/greenway-crest/',
      '/elm-thicket/',
    ],
  },
  '/northwest-dallas/': {
    href: '/neighborhood/northwest-dallas/',
    name: 'Northwest Dallas',
    parent: '/neighborhoods/',
    dropdown: ['/midway-hollow/', '/highland-north/'],
  },
  '/midway-hollow/': {
    href: '/neighborhood/midway-hollow/',
    name: 'Midway Hollow',
    parent: '/northwest-dallas/',
  },
  '/highland-north/': {
    href: '/neighborhood/highland-north/',
    name: 'Highland North',
    parent: '/northwest-dallas/',
  },
  '/highland-park/': {
    href: '/neighborhood/highland-park/',
    name: 'Highland Park',
    parent: '/park-cities/',
    dropdown: [
      '/old-highland-park/',
      [
        '/katy-trail-corridor-of-old-highland-park/',
        '/first-section-of-old-highland-park/',
        '/second-section-of-old-highland-park/',
        '/turtle-creek-acreage-of-old-highland-park/',
        '/acreage-section-of-old-highland-park/',
        '/third-section-of-old-highland-park/',
        '/fourth-section-of-old-highland-park/',
        '/hackberry-creek-acreage-of-old-highland-park/',
      ],
      '/highland-park-west-of-preston/',
      [
        '/first-section-of-highland-park-west-of-preston/',
        '/second-section-of-highland-park-west-of-preston/',
        '/third-section-of-highland-park-west-of-preston/',
        '/fourth-section-of-highland-park-west-of-preston/',
        '/fifth-section-of-highland-park-west-of-preston/',
        '/sixth-section-of-highland-park-west-of-preston/',
        '/west-park-in-highland-park-west-of-preston/',
      ],
      '/highland-park-north-of-mockingbird/',
      [
        '/mount-vernon-in-highland-park-north-of-mockingbird/',
        '/preston-place-1-in-highland-park-north-of-mockingbird/',
      ],
      '/west-highland-park/',
    ],
  },
  '/old-highland-park/': {
    href: '/neighborhood/old-highland-park/',
    name: 'Old Highland Park',
    parent: '/highland-park/',
    dropdown: [
      '/katy-trail-corridor-of-old-highland-park/',
      '/first-section-of-old-highland-park/',
      '/second-section-of-old-highland-park/',
      '/turtle-creek-acreage-of-old-highland-park/',
      '/acreage-section-of-old-highland-park/',
      '/third-section-of-old-highland-park/',
      '/fourth-section-of-old-highland-park/',
      '/hackberry-creek-acreage-of-old-highland-park/',
    ],
  },
  '/katy-trail-corridor-of-old-highland-park/': {
    href: '/neighborhood/katy-trail-corridor-of-old-highland-park/',
    name: 'Katy Trail Corridor of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/first-section-of-old-highland-park/': {
    href: '/neighborhood/first-section-of-old-highland-park/',
    name: 'First Section of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/second-section-of-old-highland-park/': {
    href: '/neighborhood/second-section-of-old-highland-park/',
    name: 'Second Section of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/turtle-creek-acreage-of-old-highland-park/': {
    href: '/neighborhood/turtle-creek-acreage-of-old-highland-park/',
    name: 'Turtle Creek Acreage of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/acreage-section-of-old-highland-park/': {
    href: '/neighborhood/acreage-section-of-old-highland-park/',
    name: 'Acreage Section of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/third-section-of-old-highland-park/': {
    href: '/neighborhood/third-section-of-old-highland-park/',
    name: 'Third Section of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/fourth-section-of-old-highland-park/': {
    href: '/neighborhood/fourth-section-of-old-highland-park/',
    name: 'Fourth Section of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/hackberry-creek-acreage-of-old-highland-park/': {
    href: '/neighborhood/hackberry-creek-acreage-of-old-highland-park/',
    name: 'Hackberry Creek Acreage of Old Highland Park',
    parent: '/old-highland-park/',
  },
  '/highland-park-west-of-preston/': {
    href: '/neighborhood/highland-park-west-of-preston/',
    name: 'Highland Park West of Preston',
    parent: '/highland-park/',
    dropdown: [
      '/first-section-of-highland-park-west-of-preston/',
      '/second-section-of-highland-park-west-of-preston/',
      '/third-section-of-highland-park-west-of-preston/',
      '/fourth-section-of-highland-park-west-of-preston/',
      '/fifth-section-of-highland-park-west-of-preston/',
      '/sixth-section-of-highland-park-west-of-preston/',
      '/west-park-in-highland-park-west-of-preston/',
    ],
  },
  '/first-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/first-section-of-highland-park-west-of-preston/',
    name: 'First Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/second-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/second-section-of-highland-park-west-of-preston/',
    name: 'Second Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/third-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/third-section-of-highland-park-west-of-preston/',
    name: 'Third Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/fourth-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/fourth-section-of-highland-park-west-of-preston/',
    name: 'Fourth Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/fifth-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/fifth-section-of-highland-park-west-of-preston/',
    name: 'Fifth Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/sixth-section-of-highland-park-west-of-preston/': {
    href: '/neighborhood/sixth-section-of-highland-park-west-of-preston/',
    name: 'Sixth Section of Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/west-park-in-highland-park-west-of-preston/': {
    href: '/neighborhood/west-park-in-highland-park-west-of-preston/',
    name: 'West Park in Highland Park',
    parent: '/highland-park-west-of-preston/',
  },
  '/highland-park-north-of-mockingbird/': {
    href: '/neighborhood/highland-park-north-of-mockingbird/',
    name: 'Highland Park North of Mockingbird',
    parent: '/highland-park/',
    dropdown: [
      '/mount-vernon-in-highland-park-north-of-mockingbird/',
      '/preston-place-1-in-highland-park-north-of-mockingbird/',
    ],
  },
  '/mount-vernon-in-highland-park-north-of-mockingbird/': {
    href: '/neighborhood/mount-vernon-in-highland-park-north-of-mockingbird/',
    name: 'Mount Vernon',
    parent: '/highland-park-north-of-mockingbird/',
  },
  '/preston-place-1-in-highland-park-north-of-mockingbird/': {
    href: '/neighborhood/preston-place-1-in-highland-park-north-of-mockingbird/',
    name: 'Preston Place 1',
    parent: '/highland-park-north-of-mockingbird/',
  },
  '/west-highland-park/': {
    href: '/neighborhood/west-highland-park/',
    name: 'West Highland Park',
    parent: '/highland-park/',
  },
  '/forest-lane-to-lbj/': {
    href: '/neighborhood/forest-lane-to-lbj/',
    name: 'Forest Lane to LBJ',
    parent: '/neighborhoods/',
    dropdown: ['/melshire-estates/'],
  },
  '/melshire-estates/': {
    href: '/neighborhood/melshire-estates/',
    name: 'Melshire Estates',
    parent: '/forest-lane-to-lbj/',
  },
  '/winnetka-heights/': {
    href: '/neighborhood/winnetka-heights/',
    name: 'Winnetka Heights',
    parent: '/oak-cliff/',
  },
  '/preston-hollow/': {
    href: '/neighborhood/preston-hollow/',
    name: 'Preston Hollow',
    parent: '/neighborhoods/',
    dropdown: [
      '/old-preston-hollow/',
      [
        '/preston-hollow-addition/',
        '/sunnybrook-estates/',
        '/meadowbrook-estates/',
        '/meadowood-estates/',
        '/maywood-estates/',
        '/inwood-park-estates/',
        '/inwood-addition-1/',
        '/inwood-addition-2/',
        '/el-parado/',
        '/preston-downs/',
        '/preston-elms/',
        '/ridgewood-addition/',
        '/dentwood-addition/',
        '/batesons/',
        '/lansdowne-estates/',
        '/woodland-estates/',
        '/radbrook-estates/',
        '/thatcher-ella-rose/',
        '/rockbrook-estates/',
        '/hillcrest-to-preston/',
      ],
      '/walnut-hill-to-forest-lane/',
      [
        '/winding-lake-neighborhood/',
        '/russwood-acres/',
        '/preston-royal/',
        '/mayflower-estates/',
        '/strait-lane/',
        '/los-arboles/',
        '/kelsey-square/',
        '/northaven/',
        '/lobello/',
        '/crest-manor-estates/',
        '/brookshire-park/',
        '/jan-mar/',
        '/royal-way/',
      ],
      '/bluffview-area/',
      [
        '/bluffview/',
        '/cochran-chapel/',
        '/shorecrest-estates/',
        '/inwood-terrace/',
        '/northwest-hills/',
        '/devonshire/',
      ],
      '/preston-hollow-east/',
      ['/biglot-addition/', '/jackson-heights/', '/mcdowell/'],
    ],
  },
  '/old-preston-hollow/': {
    href: '/neighborhood/old-preston-hollow/',
    name: 'Old Preston Hollow',
    parent: '/preston-hollow/',
    dropdown: [
      '/preston-hollow-addition/',
      '/sunnybrook-estates/',
      '/meadowbrook-estates/',
      '/meadowood-estates/',
      '/maywood-estates/',
      '/inwood-park-estates/',
      '/inwood-addition-1/',
      '/inwood-addition-2/',
      '/el-parado/',
      '/preston-downs/',
      '/preston-elms/',
      '/ridgewood-addition/',
      '/dentwood-addition/',
      '/batesons/',
      '/lansdowne-estates/',
      '/woodland-estates/',
      '/radbrook-estates/',
      '/thatcher-ella-rose/',
      '/rockbrook-estates/',
      '/hillcrest-to-preston/',
    ],
  },
  '/preston-hollow-addition/': {
    href: '/neighborhood/preston-hollow-addition/',
    name: 'Preston Hollow Addition',
    parent: '/old-preston-hollow/',
  },
  '/sunnybrook-estates/': {
    href: '/neighborhood/sunnybrook-estates/',
    name: 'Sunnybrook Estates',
    parent: '/old-preston-hollow/',
  },
  '/meadowbrook-estates/': {
    href: '/neighborhood/meadowbrook-estates/',
    name: 'Meadowbrook Estates',
    parent: '/old-preston-hollow/',
  },
  '/meadowood-estates/': {
    href: '/neighborhood/meadowood-estates/',
    name: 'Meadowood Estates',
    parent: '/old-preston-hollow/',
  },
  '/maywood-estates/': {
    href: '/neighborhood/maywood-estates/',
    name: 'Maywood Estates',
    parent: '/old-preston-hollow/',
  },
  '/inwood-park-estates/': {
    href: '/neighborhood/inwood-park-estates/',
    name: 'Inwood Park Estates',
    parent: '/old-preston-hollow/',
  },
  '/inwood-addition-1/': {
    href: '/neighborhood/inwood-addition-1/',
    name: 'Inwood Addition #1',
    parent: '/old-preston-hollow/',
  },
  '/inwood-addition-2/': {
    href: '/neighborhood/inwood-addition-2/',
    name: 'Inwood Addition #2',
    parent: '/old-preston-hollow/',
  },
  '/el-parado/': {
    href: '/neighborhood/el-parado/',
    name: 'El Parado',
    parent: '/old-preston-hollow/',
  },
  '/preston-downs/': {
    href: '/neighborhood/preston-downs/',
    name: 'Preston Downs',
    parent: '/old-preston-hollow/',
  },
  '/preston-elms/': {
    href: '/neighborhood/preston-elms/',
    name: 'Preston Elms',
    parent: '/old-preston-hollow/',
  },
  '/ridgewood-addition/': {
    href: '/neighborhood/ridgewood-addition/',
    name: 'Ridgewood Addition',
    parent: '/old-preston-hollow/',
  },
  '/dentwood-addition/': {
    href: '/neighborhood/dentwood-addition/',
    name: 'Dentwood Addition',
    parent: '/old-preston-hollow/',
  },
  '/batesons/': {
    href: '/neighborhood/batesons/',
    name: 'Batesons',
    parent: '/old-preston-hollow/',
  },
  '/lansdowne-estates/': {
    href: '/neighborhood/lansdowne-estates/',
    name: 'Lansdowne Estates',
    parent: '/old-preston-hollow/',
  },
  '/woodland-estates/': {
    href: '/neighborhood/woodland-estates/',
    name: 'Woodland Estates',
    parent: '/old-preston-hollow/',
  },
  '/radbrook-estates/': {
    href: '/neighborhood/radbrook-estates/',
    name: 'Radbrook Estates',
    parent: '/old-preston-hollow/',
  },
  '/thatcher-ella-rose/': {
    href: '/neighborhood/thatcher-ella-rose/',
    name: 'Thatcher Ella Rose',
    parent: '/old-preston-hollow/',
  },
  '/rockbrook-estates/': {
    href: '/neighborhood/rockbrook-estates/',
    name: 'Rockbrook Estates',
    parent: '/old-preston-hollow/',
  },
  '/hillcrest-to-preston/': {
    href: '/neighborhood/hillcrest-to-preston/',
    name: 'Hillcrest to Preston',
    parent: '/old-preston-hollow/',
  },
  '/walnut-hill-to-forest-lane/': {
    href: '/neighborhood/walnut-hill-to-forest-lane/',
    name: 'Walnut Hill to Forest Lane',
    parent: '/preston-hollow/',
    dropdown: [
      '/winding-lake-neighborhood/',
      '/russwood-acres/',
      '/preston-royal/',
      '/mayflower-estates/',
      '/strait-lane/',
      '/los-arboles/',
      '/kelsey-square/',
      '/northaven/',
      '/lobello/',
      '/crest-manor-estates/',
      '/brookshire-park/',
      '/jan-mar/',
      '/royal-way/',
    ],
  },
  '/winding-lake-neighborhood/': {
    href: '/neighborhood/winding-lake-neighborhood/',
    name: 'Winding Lake Neighborhood',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/russwood-acres/': {
    href: '/neighborhood/russwood-acres/',
    name: 'Russwood Acres',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/preston-royal/': {
    href: '/neighborhood/preston-royal/',
    name: 'Preston Royal',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/mayflower-estates/': {
    href: '/neighborhood/mayflower-estates/',
    name: 'Mayflower Estates',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/strait-lane/': {
    href: '/neighborhood/strait-lane/',
    name: 'Strait Lane',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/los-arboles/': {
    href: '/neighborhood/los-arboles/',
    name: 'Los Arboles',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/kelsey-square/': {
    href: '/neighborhood/kelsey-square/',
    name: 'Kelsey Square',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/northaven/': {
    href: '/neighborhood/northaven/',
    name: 'Northaven',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/lobello/': {
    href: '/neighborhood/lobello/',
    name: 'Lobello Estates',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/crest-manor-estates/': {
    href: '/neighborhood/crest-manor-estates/',
    name: 'Crest Manor Estates',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/brookshire-park/': {
    href: '/neighborhood/brookshire-park/',
    name: 'Brookshire Park',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/mcdowell/': {
    href: '/neighborhood/mcdowell/',
    name: 'McDowell',
    parent: '/preston-hollow-east/',
  },
  '/jan-mar/': {
    href: '/neighborhood/jan-mar/',
    name: 'Jan Mar',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/jackson-heights/': {
    href: '/neighborhood/jackson-heights/',
    name: 'Jackson Heights',
    parent: '/preston-hollow-east/',
  },
  '/royal-way/': {
    href: '/neighborhood/royal-way/',
    name: 'Royal Way',
    parent: '/walnut-hill-to-forest-lane/',
  },
  '/bluffview-area/': {
    href: '/neighborhood/bluffview-area/',
    name: 'Bluffview Area',
    parent: '/preston-hollow/',
    dropdown: [
      '/bluffview/',
      '/cochran-chapel/',
      '/shorecrest-estates/',
      '/inwood-terrace/',
      '/northwest-hills/',
      '/devonshire/',
    ],
  },
  '/bluffview/': {
    href: '/neighborhood/bluffview/',
    name: 'Bluffview',
    parent: '/bluffview-area/',
  },
  '/cochran-chapel/': {
    href: '/neighborhood/cochran-chapel/',
    name: 'Cochran Chapel',
    parent: '/bluffview-area/',
  },
  '/shorecrest-estates/': {
    href: '/neighborhood/shorecrest-estates/',
    name: 'Shorecrest Estates',
    parent: '/bluffview-area/',
  },
  '/inwood-terrace/': {
    href: '/neighborhood/inwood-terrace/',
    name: 'Inwood Terrace',
    parent: '/bluffview-area/',
  },
  '/northwest-hills/': {
    href: '/neighborhood/northwest-hills/',
    name: 'Northwest Hills',
    parent: '/bluffview-area/',
  },
  '/devonshire/': {
    href: '/neighborhood/devonshire/',
    name: 'Devonshire',
    parent: '/bluffview-area/',
  },
  '/turtle-creek-corridor/': {
    href: '/neighborhood/turtle-creek-corridor/',
    name: 'Turtle Creek Area',
    parent: '/neighborhoods/',
    dropdown: [
      '/turtle-creek-highrise-area/',
      '/katy-trail-turtle-creek-area/',
      [
        '/turtle-creek-park/',
        '/place-des-vosges/',
        '/northern-hills/',
        '/park-bridge-court/',
        '/northern-heights/',
        '/turtle-creek-bend/',
        '/christopher-place/',
      ],
      '/cole-mckinney-area/',
      ['/west-village/', '/knox-to-blackburn/', '/state-thomas/'],
      '/oak-lawn/',
      [
        '/golf-grounds/',
        '/cedar-springs/',
        '/oak-lawn-heights/',
        '/perry-heights/',
      ],
    ],
  },
  '/turtle-creek-highrise-area/': {
    href: '/neighborhood/turtle-creek-highrise-area/',
    name: 'Turtle Creek Highrise Area',
    parent: '/turtle-creek-corridor/',
  },
  '/katy-trail-turtle-creek-area/': {
    href: '/neighborhood/katy-trail-turtle-creek-area/',
    name: 'Katy Trail / Turtle Creek Area',
    parent: '/turtle-creek-corridor/',
    dropdown: [
      '/turtle-creek-park/',
      '/place-des-vosges/',
      '/northern-hills/',
      '/park-bridge-court/',
      '/northern-heights/',
      '/turtle-creek-bend/',
      '/christopher-place/',
    ],
  },
  '/turtle-creek-park/': {
    href: '/neighborhood/turtle-creek-park/',
    name: 'Turtle Creek Park',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/place-des-vosges/': {
    href: '/neighborhood/place-des-vosges/',
    name: 'Place Des Vosges',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/northern-hills/': {
    href: '/neighborhood/northern-hills/',
    name: 'Northern Hills',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/park-bridge-court/': {
    href: '/neighborhood/park-bridge-court/',
    name: 'Park Bridge Court',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/northern-heights/': {
    href: '/neighborhood/northern-heights/',
    name: 'Northern Heights',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/turtle-creek-bend/': {
    href: '/neighborhood/turtle-creek-bend/',
    name: 'Turtle Creek Bend',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/christopher-place/': {
    href: '/neighborhood/christopher-place/',
    name: 'Christopher Place',
    parent: '/katy-trail-turtle-creek-area/',
  },
  '/cole-mckinney-area/': {
    href: '/neighborhood/cole-mckinney-area/',
    name: 'Cole / McKinney Area',
    parent: '/turtle-creek-corridor/',
    dropdown: ['/west-village/', '/knox-to-blackburn/', '/state-thomas/'],
  },
  '/west-village/': {
    href: '/neighborhood/west-village/',
    name: 'West Village',
    parent: '/cole-mckinney-area/',
  },
  '/knox-to-blackburn/': {
    href: '/neighborhood/knox-to-blackburn/',
    name: 'Knox to Blackburn',
    parent: '/cole-mckinney-area/',
  },
  '/state-thomas/': {
    href: '/neighborhood/state-thomas/',
    name: 'State Thomas',
    parent: '/cole-mckinney-area/',
  },
  '/oak-lawn/': {
    href: '/neighborhood/oak-lawn/',
    name: 'Oak Lawn',
    parent: '/turtle-creek-corridor/',
    dropdown: [
      '/golf-grounds/',
      '/cedar-springs/',
      '/oak-lawn-heights/',
      '/perry-heights/',
    ],
  },
  '/golf-grounds/': {
    href: '/neighborhood/golf-grounds/',
    name: 'Golf Grounds',
    parent: '/oak-lawn/',
  },
  '/cedar-springs/': {
    href: '/neighborhood/cedar-springs/',
    name: 'Cedar Springs',
    parent: '/oak-lawn/',
  },
  '/oak-lawn-heights/': {
    href: '/neighborhood/oak-lawn-heights/',
    name: 'Oak Lawn Heights',
    parent: '/oak-lawn/',
  },
  '/perry-heights/': {
    href: '/neighborhood/perry-heights/',
    name: 'Perry Heights',
    parent: '/oak-lawn/',
  },
  '/park-cities/': {
    href: '/neighborhood/park-cities/',
    name: 'Park Cities',
    parent: '/neighborhoods/',
    dropdown: ['/highland-park/', '/university-park/'],
  },
  '/university-park/': {
    href: '/neighborhood/university-park/',
    name: 'University Park',
    parent: '/park-cities/',
    dropdown: [
      '/st-andrews-place/',
      '/windsor-place/',
      '/volk-estates/',
      ['/brookside-estates/', '/university-park-estates/', '/troths-addition/'],
      '/francis-daniel-park/',
      '/westminster-place/',
      '/university-heights/',
      [
        '/university-heights-original/',
        '/university-heights-no-2-3/',
        '/university-heights-no-4-5/',
        '/university-heights-no-6-7/',
      ],
      '/stratford-manor/',
      '/potomac-park/',
      '/loma-linda/',
      '/idlewild/',
      '/preston-homes-addition/',
      '/university-highlands/',
      '/armstrong-fairway/',
      '/highland-park-high-school/',
      '/smu-neighborhoods-east/',
      '/smu-neighborhoods-west/',
      '/smu-heights/',
      '/caruth-hills/',
      '/preston-place-3/',
    ],
  },
  '/st-andrews-place/': {
    href: '/neighborhood/st-andrews-place/',
    name: 'St. Andrews Place',
    parent: '/university-park/',
  },
  '/windsor-place/': {
    href: '/neighborhood/windsor-place/',
    name: 'Windsor Place',
    parent: '/university-park/',
  },
  '/volk-estates/': {
    href: '/neighborhood/volk-estates/',
    name: 'Volk Estates',
    parent: '/university-park/',
    dropdown: [
      '/brookside-estates/',
      '/university-park-estates/',
      '/troths-addition/',
    ],
  },
  '/brookside-estates/': {
    href: '/neighborhood/brookside-estates/',
    name: 'Brookside Estates',
    parent: '/volk-estates/',
  },
  '/university-park-estates/': {
    href: '/neighborhood/university-park-estates/',
    name: 'University Park Estates',
    parent: '/volk-estates/',
  },
  '/troths-addition/': {
    href: '/neighborhood/troths-addition/',
    name: "Troth's Addition",
    parent: '/volk-estates/',
  },
  '/francis-daniel-park/': {
    href: '/neighborhood/francis-daniel-park/',
    name: 'Francis Daniel Park',
    parent: '/university-park/',
  },
  '/westminster-place/': {
    href: '/neighborhood/westminster-place/',
    name: 'Westminster Place',
    parent: '/university-park/',
  },
  '/university-heights/': {
    href: '/neighborhood/university-heights/',
    name: 'University Heights',
    parent: '/university-park/',
    dropdown: [
      '/university-heights-original/',
      '/university-heights-no-2-3/',
      '/university-heights-no-4-5/',
      '/university-heights-no-6-7/',
    ],
  },
  '/university-heights-original/': {
    href: '/neighborhood/university-heights-original/',
    name: 'University Heights Original',
    parent: '/university-heights/',
  },
  '/university-heights-no-2-3/': {
    href: '/neighborhood/university-heights-no-2-3/',
    name: 'University Heights No 2 & 3',
    parent: '/university-heights/',
  },
  '/university-heights-no-4-5/': {
    href: '/neighborhood/university-heights-no-4-5/',
    name: 'University Heights No 4 & 5',
    parent: '/university-heights/',
  },
  '/university-heights-no-6-7/': {
    href: '/neighborhood/university-heights-no-6-7/',
    name: 'University Heights No 6 & 7',
    parent: '/university-heights/',
  },
  '/stratford-manor/': {
    href: '/neighborhood/stratford-manor/',
    name: 'Stratford Manor',
    parent: '/university-park/',
  },
  '/potomac-park/': {
    href: '/neighborhood/potomac-park/',
    name: 'Potomac Park',
    parent: '/university-park/',
  },
  '/loma-linda/': {
    href: '/neighborhood/loma-linda/',
    name: 'Loma Linda',
    parent: '/university-park/',
  },
  '/idlewild/': {
    href: '/neighborhood/idlewild/',
    name: 'Idlewild',
    parent: '/university-park/',
  },
  '/preston-homes-addition/': {
    href: '/neighborhood/preston-homes-addition/',
    name: 'Preston Homes Addition',
    parent: '/university-park/',
  },
  '/university-highlands/': {
    href: '/neighborhood/university-highlands/',
    name: 'University Highlands',
    parent: '/university-park/',
  },
  '/armstrong-fairway/': {
    href: '/neighborhood/armstrong-fairway/',
    name: 'Armstrong Fairway',
    parent: '/university-park/',
  },
  '/highland-park-high-school/': {
    href: '/neighborhood/highland-park-high-school/',
    name: 'Highland Park High School',
    parent: '/university-park/',
  },
  '/smu-neighborhoods-east/': {
    href: '/neighborhood/smu-neighborhoods-east/',
    name: 'SMU Neighborhoods East',
    parent: '/university-park/',
  },
  '/smu-neighborhoods-west/': {
    href: '/neighborhood/smu-neighborhoods-west/',
    name: 'SMU Neighborhoods West',
    parent: '/university-park/',
  },
  '/smu-heights/': {
    href: '/neighborhood/smu-heights/',
    name: 'SMU Heights',
    parent: '/university-park/',
  },
  '/caruth-hills/': {
    href: '/neighborhood/caruth-hills/',
    name: 'Caruth Hills',
    parent: '/university-park/',
  },
  '/preston-place-3/': {
    href: '/neighborhood/preston-place-3/',
    name: 'Preston Place 3',
    parent: '/university-park/',
  },
  '/greenway-parks/': {
    href: '/neighborhood/greenway-parks/',
    name: 'Greenway Parks',
    parent: '/neighborhoods/',
  },
  '/munger-place/': {
    href: '/neighborhood/munger-place/',
    name: 'Munger Place',
    parent: '/old-east-dallas/',
    dropdown: [
      '/munger-place-historic-district/',
      '/swiss-avenue-historic-district/',
    ],
  },
  '/munger-place-historic-district/': {
    href: '/neighborhood/munger-place-historic-district/',
    name: 'Munger Place Historic District',
    parent: '/munger-place/',
    dropdown: ['/centennial-photographs-of-munger-place-homes/'],
  },
  '/centennial-photographs-of-munger-place-homes/': {
    href: '/centennial-photographs-of-munger-place-homes/',
    name: 'Centennial Photographs',
    parent: '/munger-place-historic-district/',
  },
  '/swiss-avenue-historic-district/': {
    href: '/neighborhood/swiss-avenue-historic-district/',
    name: 'Swiss Avenue Historic District',
    parent: '/munger-place/',
    dropdown: ['/centennial-photographs-of-swiss-avenue-homes/'],
  },
  '/centennial-photographs-of-swiss-avenue-homes/': {
    href: '/centennial-photographs-of-swiss-avenue-homes/',
    name: 'Centennial Photographs',
    parent: '/swiss-avenue-historic-district/',
  },
  '/east-dallas/': {
    href: '/neighborhood/east-dallas/',
    name: 'East Dallas',
    parent: '/neighborhoods/',
    dropdown: [
      '/white-rock-lake/',
      [
        '/peninsula/',
        '/emerald-isle/',
        '/chapel-hill-estates/',
        '/the-cloisters/',
        '/shore-acres-addition/',
        ['/west-lawther-drive/'],
        '/garland-road/',
        '/maplewood/',
        '/greencove-estates/',
      ],
      '/lakewood/',
      [
        '/bob-o-links-downs/',
        '/lakewood-pasadena/',
        '/lakewood-conservation-district/',
      ],
      '/lakewood-hills/',
      '/lakewood-heights/',
      '/forest-hills/',
      '/little-forest-hills/',
      '/lake-park-estates/',
      '/hollywood-heights-santa-monica/',
      '/old-east-dallas/',
      [
        '/munger-place/',
        '/swiss-avenue-historic-district/',
        '/bryan-parkway-in-munger-place-heights/',
        '/junius-heights/',
        '/peaks-addition/',
        '/belmont-conservation-district/',
        '/bryan-place/',
        '/peaks-addition/',
        '/wilshire-heights/',
        '/henderson-addition/',
        '/cochran-heights/',
        '/deere-park/',
        '/parks-estates/',
      ],
      '/greenland-hills/',
      '/vickery-place/',
      '/deep-ellum/',
      '/old-lake-highlands/',
      '/mount-auburn/',
    ],
  },
  '/white-rock-lake/': {
    href: '/neighborhood/white-rock-lake/',
    name: 'White Rock Lake',
    parent: '/east-dallas/',
    dropdown: [
      '/peninsula/',
      '/emerald-isle/',
      '/chapel-hill-estates/',
      '/the-cloisters/',
      '/shore-acres-addition/',
      ['/west-lawther-drive/'],
      '/garland-road/',
      '/maplewood/',
      '/greencove-estates/',
    ],
  },
  '/west-lawther-drive/': {
    href: '/neighborhood/west-lawther-drive/',
    name: 'West Lawther Drive',
    parent: '/shore-acres-addition/',
  },
  '/peninsula/': {
    href: '/neighborhood/peninsula/',
    name: 'Peninsula',
    parent: '/white-rock-lake/',
  },
  '/emerald-isle/': {
    href: '/neighborhood/emerald-isle/',
    name: 'Emerald Isle',
    parent: '/white-rock-lake/',
  },
  '/chapel-hill-estates/': {
    href: '/neighborhood/chapel-hill-estates/',
    name: 'Chapel Hill Estates',
    parent: '/white-rock-lake/',
  },
  '/the-cloisters/': {
    href: '/neighborhood/the-cloisters/',
    name: 'The Cloisters',
    parent: '/white-rock-lake/',
  },
  '/shore-acres-addition/': {
    href: '/neighborhood/shore-acres-addition/',
    name: 'Shore Acres Addition',
    parent: '/white-rock-lake/',
    dropdown: ['/west-lawther-drive/'],
  },
  '/garland-road/': {
    href: '/neighborhood/garland-road/',
    name: 'Garland Road',
    parent: '/white-rock-lake/',
  },
  '/maplewood/': {
    href: '/neighborhood/maplewood/',
    name: 'Maplewood',
    parent: '/white-rock-lake/',
  },
  '/greencove-estates/': {
    href: '/neighborhood/greencove-estates/',
    name: 'Green Cove Estates',
    parent: '/white-rock-lake/',
  },
  '/little-forest-hills/': {
    href: '/neighborhood/little-forest-hills/',
    name: 'Little Forest Hills',
    parent: '/east-dallas/',
  },
  '/lake-park-estates/': {
    href: '/neighborhood/lake-park-estates/',
    name: 'Lake Park Estates',
    parent: '/east-dallas/',
  },
  '/forest-hills/': {
    href: '/neighborhood/forest-hills/',
    name: 'Forest Hills',
    parent: '/east-dallas/',
  },
  '/lakewood/': {
    href: '/neighborhood/lakewood/',
    name: 'Lakewood',
    parent: '/east-dallas/',
    dropdown: [
      '/bob-o-links-downs/',
      '/lakewood-pasadena/',
      '/lakewood-conservation-district/',
      ['/country-club-circle/'],
    ],
  },
  '/bob-o-links-downs/': {
    href: '/neighborhood/bob-o-links-downs/',
    name: 'Bob O Links Downs',
    parent: '/lakewood/',
  },
  '/lakewood-pasadena/': {
    href: '/neighborhood/lakewood-pasadena/',
    name: 'Lakewood Pasadena',
    parent: '/lakewood/',
  },
  '/lakewood-conservation-district/': {
    href: '/neighborhood/lakewood-conservation-district/',
    name: 'Lakewood Conservation District',
    parent: '/lakewood/',
    dropdown: ['/country-club-circle/'],
  },
  '/old-east-dallas/': {
    href: '/neighborhood/old-east-dallas/',
    name: 'Old East Dallas',
    parent: '/east-dallas/',
    dropdown: [
      '/munger-place/',
      '/swiss-avenue-historic-district/',
      '/bryan-parkway-in-munger-place-heights/',
      '/junius-heights/',
      '/peaks-addition/',
      '/belmont-conservation-district/',
      '/bryan-place/',
      '/peaks-addition/',
      '/wilshire-heights/',
      '/henderson-addition/',
      '/cochran-heights/',
      '/deere-park/',
      '/parks-estates/',
    ],
  },
  '/cochran-heights/': {
    href: '/neighborhood/cochran-heights/',
    name: 'Chochran Heights',
    parent: '/old-east-dallas/',
  },
  '/parks-estates/': {
    href: '/neighborhood/parks-estates/',
    name: 'Parks Estates',
    parent: '/old-east-dallas/',
  },
  '/bryan-place/': {
    href: '/neighborhood/bryan-place/',
    name: 'Bryan Place',
    parent: '/old-east-dallas/',
  },
  '/bryan-parkway-in-munger-place-heights/': {
    href: '/neighborhood/bryan-parkway-in-munger-place-heights/',
    name: 'Bryan Parkway in Munger Place Heights Neighborhood',
    parent: '/old-east-dallas/',
  },
  '/junius-heights/': {
    href: '/neighborhood/junius-heights/',
    name: 'Junius Heights',
    parent: '/old-east-dallas/',
  },
  '/belmont-conservation-district/': {
    href: '/neighborhood/belmont-conservation-district/',
    name: 'Belmont Conservation District',
    parent: '/old-east-dallas/',
  },
  '/peaks-addition/': {
    href: '/neighborhood/peaks-addition/',
    name: "Peak's Suburban Addition Historic District",
    parent: '/old-east-dallas/',
  },
  '/deere-park/': {
    href: '/neighborhood/deere-park/',
    name: 'Deere Park',
    parent: '/old-east-dallas/',
  },
  '/mount-auburn/': {
    href: '/neighborhood/mount-auburn/',
    name: 'Mount Auburn',
    parent: '/east-dallas/',
  },
  '/hollywood-heights-santa-monica/': {
    href: '/neighborhood/hollywood-heights-santa-monica/',
    name: 'Hollywood Heights Santa Monica',
    parent: '/east-dallas/',
  },
  '/henderson-addition/': {
    href: '/neighborhood/henderson-addition/',
    name: 'Henderson',
    parent: '/old-east-dallas/',
  },
  '/deep-ellum/': {
    href: '/neighborhood/deep-ellum/',
    name: 'Deep Ellum',
    parent: '/east-dallas/',
  },
  '/wilshire-heights/': {
    href: '/neighborhood/wilshire-heights/',
    name: 'Wilshire Heights',
    parent: '/old-east-dallas/',
  },
  '/old-lake-highlands/': {
    href: '/neighborhood/old-lake-highlands/',
    name: 'Old Lake Highlands',
    parent: '/east-dallas/',
  },
  '/greenland-hills/': {
    href: '/neighborhood/greenland-hills/',
    name: 'Greenland Hills',
    parent: '/east-dallas/',
  },
  '/vickery-place/': {
    href: '/neighborhood/vickery-place/',
    name: 'Vickery Place',
    parent: '/east-dallas/',
  },
  '/lakewood-hills/': {
    href: '/neighborhood/lakewood-hills/',
    name: 'Lakewood Hills',
    parent: '/east-dallas/',
  },
  '/lakewood-heights/': {
    href: '/neighborhood/lakewood-heights/',
    name: 'Lakewood Heights',
    parent: '/east-dallas/',
  },
  '/downtown-dallas/': {
    href: '/neighborhood/downtown-dallas/',
    name: 'Downtown Dallas',
    parent: '/neighborhoods/',
  },
  '/far-north-dallas/': {
    href: '/neighborhood/far-north-dallas/',
    name: 'Far North Dallas',
    parent: '/neighborhoods/',
    dropdown: [
      '/glen-abbey/',
      '/bent-tree/',
      '/northwood-hills/',
      '/williamsburg-estates/',
    ],
  },
  '/glen-abbey/': {
    href: '/neighborhood/glen-abbey/',
    name: 'Glen Abbey',
    parent: '/far-north-dallas/',
  },
  '/bent-tree/': {
    href: '/neighborhood/bent-tree/',
    name: 'Bent Tree',
    parent: '/far-north-dallas/',
  },
  '/northwood-hills/': {
    href: '/neighborhood/northwood-hills/',
    name: 'Northwood Hills',
    parent: '/far-north-dallas/',
  },
  '/williamsburg-estates/': {
    href: '/neighborhood/williamsburg-estates/',
    name: 'Williamsburg Estates',
    parent: '/far-north-dallas/',
  },
  '/merriman-park-university-manor/': {
    href: '/neighborhood/merriman-park-university-manor/',
    name: 'Merriam Park-University Manor',
    parent: '/neighborhoods/',
  },
  '/greenway-crest/': {
    href: '/neighborhood/greenway-crest/',
    name: 'Greenway Crest',
    parent: '/neighborhoods/',
  },
  '/elm-thicket/': {
    href: '/neighborhood/elm-thicket/',
    name: 'Elm Thicket',
    parent: '/neighborhoods/',
  },
  '/outside-of-dallas/': {
    href: '/neighborhood/outside-of-dallas/',
    name: 'Outside of Dallas',
    parent: '/neighborhoods/',
    dropdown: [
      '/rivercrest-bluffs/',
      '/vaquero-club-texas/',
      '/allen-texas/',
      ['/montgomery-farm/'],
      '/parker-texas/',
      '/cedar-hill-texas/',
      '/garland-texas/',
      '/big-sky-texas/',
    ],
  },
  '/rivercrest-bluffs/': {
    href: '/neighborhood/rivercrest-bluffs/',
    name: 'Rivercrest Bluffs',
    parent: '/outside-of-dallas/',
  },
  '/vaquero-club-texas/': {
    href: '/neighborhood/vaquero-club-texas/',
    name: 'Vaquero Club, Texas',
    parent: '/outside-of-dallas/',
  },
  '/allen-texas/': {
    href: '/neighborhood/allen-texas/',
    name: 'Allen, Texas',
    parent: '/outside-of-dallas/',
    dropdown: ['/montgomery-farm/'],
  },
  '/montgomery-farm/': {
    href: '/neighborhood/montgomery-farm/',
    name: 'Montgomery Farm',
    parent: '/allen-texas/',
  },
  '/parker-texas/': {
    href: '/neighborhood/parker-texas/',
    name: 'Parker, Texas',
    parent: '/outside-of-dallas/',
  },
  '/cedar-hill-texas/': {
    href: '/neighborhood/cedar-hill-texas/',
    name: 'Cedar Hill, Texas',
    parent: '/outside-of-dallas/',
  },
  '/garland-texas/': {
    href: '/neighborhood/garland-texas/',
    name: 'Garland, Texas',
    parent: '/outside-of-dallas/',
  },
  '/big-sky-texas/': {
    href: '/neighborhood/big-sky-texas/',
    name: 'Big Sky, Texas',
    parent: '/outside-of-dallas/',
  },
  '/oak-cliff/': {
    href: '/neighborhood/oak-cliff/',
    name: 'Oak Cliff',
    parent: '/neighborhoods/',
    dropdown: [
      '/lake-cliff/',
      '/kessler-woods/',
      '/kessler-park/',
      '/winnetka-heights/',
    ],
  },
  '/lake-cliff/': {
    href: '/neighborhood/lake-cliff/',
    name: 'Lake Cliff',
    parent: '/oak-cliff/',
  },
  '/kessler-woods/': {
    href: '/neighborhood/kessler-woods/',
    name: 'Kessler Woods',
    parent: '/oak-cliff/',
  },
  '/kessler-park/': {
    href: '/neighborhood/kessler-park/',
    name: 'Kessler Park',
    parent: '/oak-cliff/',
  },
  '/lake-highlands/': {
    href: '/neighborhood/lake-highlands/',
    name: 'Lake Highlands',
    parent: '/neighborhoods/',
    dropdown: ['/urban-reserve/'],
  },
  '/urban-reserve/': {
    href: '/neighborhood/urban-reserve/',
    name: 'Urban Reserve',
    parent: '/lake-highlands/',
  },
  '/preston-hollow-east/': {
    href: '/neighborhood/preston-hollow-east/',
    name: 'Preston Hollow East',
    dropdown: ['/biglot-addition/', '/jackson-heights/', '/mcdowell/'],
    parent: '/preston-hollow/',
  },
  '/biglot-addition/': {
    href: '/neighborhood/biglot-addition/',
    name: 'Biglot Addition',
    parent: '/preston-hollow-east/',
  },
  '/country-club-circle/': {
    href: '/neighborhood/country-club-circle/',
    name: 'Country Club Circle',
    parent: '/lakewood-conservation-district/',
  },
  '/alaska/': {
    href: '/coast-to-coast/alaska/',
    name: 'Alaska Architecture',
    parent: '/architecture-united-states/',
  },
  '/arizona/': {
    href: '/coast-to-coast/arizona/',
    name: 'Arizona Architecture',
    parent: '/architecture-united-states/',
  },
  '/arkansas/': {
    href: '/coast-to-coast/arkansas/',
    name: 'Arkansas Architecture',
    parent: '/architecture-united-states/',
  },
  '/california/': {
    href: '/coast-to-coast/california/',
    name: 'California Architecture',
    parent: '/architecture-united-states/',
  },
  '/colorado/': {
    href: '/coast-to-coast/colorado/',
    name: 'Colorado Architecture',
    parent: '/architecture-united-states/',
  },
  '/connecticut/': {
    href: '/coast-to-coast/connecticut/',
    name: 'Connecticut Architecture',
    parent: '/architecture-united-states/',
  },
  '/delaware/': {
    href: '/coast-to-coast/delaware/',
    name: 'Delaware Architecture',
    parent: '/architecture-united-states/',
  },
  '/florida/': {
    href: '/coast-to-coast/florida/',
    name: 'Florida Architecture',
    parent: '/architecture-united-states/',
  },
  '/georgia/': {
    href: '/coast-to-coast/georgia/',
    name: 'Georgia Architecture',
    parent: '/architecture-united-states/',
  },
  '/hawaii/': {
    href: '/coast-to-coast/hawaii/',
    name: 'Hawaii Architecture',
    parent: '/architecture-united-states/',
  },
  '/idaho/': {
    href: '/coast-to-coast/idaho/',
    name: 'Idaho Architecture',
    parent: '/architecture-united-states/',
  },
  '/illinois/': {
    href: '/coast-to-coast/illinois/',
    name: 'Illinois Architecture',
    parent: '/architecture-united-states/',
  },
  '/indiana/': {
    href: '/coast-to-coast/indiana/',
    name: 'Indiana Architecture',
    parent: '/architecture-united-states/',
  },
  '/iowa/': {
    href: '/coast-to-coast/iowa/',
    name: 'Iowa Architecture',
    parent: '/architecture-united-states/',
  },
  '/kansas/': {
    href: '/coast-to-coast/kansas/',
    name: 'Kansas Architecture',
    parent: '/architecture-united-states/',
  },
  '/kentucky/': {
    href: '/coast-to-coast/kentucky/',
    name: 'Kentucky Architecture',
    parent: '/architecture-united-states/',
  },
  '/louisiana/': {
    href: '/coast-to-coast/louisiana/',
    name: 'Louisiana Architecture',
    parent: '/architecture-united-states/',
  },
  '/maine/': {
    href: '/coast-to-coast/maine/',
    name: 'Maine Architecture',
    parent: '/architecture-united-states/',
  },
  '/maryland/': {
    href: '/coast-to-coast/maryland/',
    name: 'Maryland Architecture',
    parent: '/architecture-united-states/',
  },
  '/massachusetts/': {
    href: '/coast-to-coast/massachusetts/',
    name: 'Massachusetts Architecture',
    parent: '/architecture-united-states/',
  },
  '/michigan/': {
    href: '/coast-to-coast/michigan/',
    name: 'Michigan Architecture',
    parent: '/architecture-united-states/',
  },
  '/minnesota/': {
    href: '/coast-to-coast/minnesota/',
    name: 'Minnesota Architecture',
    parent: '/architecture-united-states/',
  },
  '/mississippi/': {
    href: '/coast-to-coast/mississippi/',
    name: 'Mississippi Architecture',
    parent: '/architecture-united-states/',
  },
  '/missouri/': {
    href: '/coast-to-coast/missouri/',
    name: 'Missouri Architecture',
    parent: '/architecture-united-states/',
  },
  '/montana/': {
    href: '/coast-to-coast/montana/',
    name: 'Montana Architecture',
    parent: '/architecture-united-states/',
  },
  '/nebraska/': {
    href: '/coast-to-coast/nebraska/',
    name: 'Nebraska Architecture',
    parent: '/architecture-united-states/',
  },
  '/nevada/': {
    href: '/coast-to-coast/nevada/',
    name: 'Nevada Architecture',
    parent: '/architecture-united-states/',
  },
  '/new-hampshire/': {
    href: '/coast-to-coast/new-hampshire/',
    name: 'New Hampshire Architecture',
    parent: '/architecture-united-states/',
  },
  '/new-jersey/': {
    href: '/coast-to-coast/new-jersey/',
    name: 'New Jersey Architecture',
    parent: '/architecture-united-states/',
  },
  '/new-mexico/': {
    href: '/coast-to-coast/new-mexico/',
    name: 'New Mexico Architecture',
    parent: '/architecture-united-states/',
  },
  '/new-york/': {
    href: '/coast-to-coast/new-york/',
    name: 'New York Architecture',
    parent: '/architecture-united-states/',
  },
  '/north-carolina/': {
    href: '/coast-to-coast/north-carolina/',
    name: 'North Carolina Architecture',
    parent: '/architecture-united-states/',
  },
  '/north-dakota/': {
    href: '/coast-to-coast/north-dakota/',
    name: 'North Dakota Architecture',
    parent: '/architecture-united-states/',
  },
  '/ohio/': {
    href: '/coast-to-coast/ohio/',
    name: 'Ohio Architecture',
    parent: '/architecture-united-states/',
  },
  '/oklahoma/': {
    href: '/coast-to-coast/oklahoma/',
    name: 'Oklahoma Architecture',
    parent: '/architecture-united-states/',
  },
  '/oregon/': {
    href: '/coast-to-coast/oregon/',
    name: 'Oregon Architecture',
    parent: '/architecture-united-states/',
  },
  '/pennsylvania/': {
    href: '/coast-to-coast/pennsylvania/',
    name: 'Pennsylvania Architecture',
    parent: '/architecture-united-states/',
  },
  '/rhode-island/': {
    href: '/coast-to-coast/rhode-island/',
    name: 'Rhode Island Architecture',
    parent: '/architecture-united-states/',
  },
  '/south-carolina/': {
    href: '/coast-to-coast/south-carolina/',
    name: 'South Carolina Architecture',
    parent: '/architecture-united-states/',
  },
  '/south-dakota/': {
    href: '/coast-to-coast/south-dakota/',
    name: 'South Dakota Architecture',
    parent: '/architecture-united-states/',
  },
  '/tennessee/': {
    href: '/coast-to-coast/tennessee/',
    name: 'Tennessee Architecture',
    parent: '/architecture-united-states/',
  },
  '/texas/': {
    href: '/coast-to-coast/texas/',
    name: 'Texas Architecture',
    parent: '/architecture-united-states/',
  },
  '/utah/': {
    href: '/coast-to-coast/utah/',
    name: 'Utah Architecture',
    parent: '/architecture-united-states/',
  },
  '/vermont/': {
    href: '/coast-to-coast/vermont/',
    name: 'Vermont Architecture',
    parent: '/architecture-united-states/',
  },
  '/virginia/': {
    href: '/coast-to-coast/virginia/',
    name: 'Virginia Architecture',
    parent: '/architecture-united-states/',
  },
  '/washington/': {
    href: '/coast-to-coast/washington/',
    name: 'Washington Architecture',
    parent: '/architecture-united-states/',
  },
  '/west-virginia/': {
    href: '/coast-to-coast/west-virginia/',
    name: 'West Virginia Architecture',
    parent: '/architecture-united-states/',
  },
  '/wisconsin/': {
    href: '/coast-to-coast/wisconsin/',
    name: 'Wisconsin Architecture',
    parent: '/architecture-united-states/',
  },
  '/wyoming/': {
    href: '/coast-to-coast/wyoming/',
    name: 'Wyoming Architecture',
    parent: '/architecture-united-states/',
  },
  '/aspen/': {
    href: '/coast-to-coast/aspen/',
    name: 'Aspen Architecture',
    parent: '/architecture-cities/',
  },
  '/atlanta/': {
    href: '/coast-to-coast/atlanta/',
    name: 'Atlanta Architecture',
    parent: '/architecture-cities/',
  },
  '/austin/': {
    href: '/coast-to-coast/austin/',
    name: 'Austin Architecture',
    parent: '/architecture-cities/',
  },
  '/baltimore/': {
    href: '/coast-to-coast/baltimore/',
    name: 'Baltimore Architecture',
    parent: '/architecture-cities/',
  },
  '/beverly-hills/': {
    href: '/coast-to-coast/beverly-hills/',
    name: 'Beverly Hills Architecture',
    parent: '/architecture-cities/',
  },
  '/big-sky/': {
    href: '/coast-to-coast/big-sky/',
    name: 'Big Sky Architecture',
    parent: '/architecture-cities/',
  },
  '/boston/': {
    href: '/coast-to-coast/boston/',
    name: 'Boston Architecture',
    parent: '/architecture-cities/',
  },
  '/boulder/': {
    href: '/coast-to-coast/boulder/',
    name: 'Boulder Architecture',
    parent: '/architecture-cities/',
  },
  '/bozeman/': {
    href: '/coast-to-coast/bozeman/',
    name: 'Bozeman Architecture',
    parent: '/architecture-cities/',
  },
  '/chattanooga/': {
    href: '/coast-to-coast/chattanooga/',
    name: 'Chattanooga Architecture',
    parent: '/architecture-cities/',
  },
  '/chevy-chase/': {
    href: '/coast-to-coast/chevy-chase/',
    name: 'Chevy Chase Architecture',
    parent: '/architecture-cities/',
  },
  '/chicago/': {
    href: '/coast-to-coast/chicago/',
    name: 'Chicago Architecture',
    parent: '/architecture-cities/',
  },
  '/cincinnati/': {
    href: '/coast-to-coast/cincinnati/',
    name: 'Cincinnati Architecture',
    parent: '/architecture-cities/',
  },
  '/cleveland/': {
    href: '/coast-to-coast/cleveland/',
    name: 'Cleveland Architecture',
    parent: '/architecture-cities/',
  },
  '/dallas/': {
    href: '/coast-to-coast/dallas/',
    name: 'Dallas Architecture',
    parent: '/architecture-cities/',
  },
  '/denver/': {
    href: '/coast-to-coast/denver/',
    name: 'Denver Architecture',
    parent: '/architecture-cities/',
  },
  '/des-moines/': {
    href: '/coast-to-coast/des-moines/',
    name: 'Des Moines Architecture',
    parent: '/architecture-cities/',
  },
  '/duluth/': {
    href: '/coast-to-coast/duluth/',
    name: 'Duluth Architecture',
    parent: '/architecture-cities/',
  },
  '/fairfield/': {
    href: '/coast-to-coast/fairfield/',
    name: 'Fairfield Architecture',
    parent: '/architecture-cities/',
  },
  '/franklin/': {
    href: '/coast-to-coast/franklin/',
    name: 'Franklin Architecture',
    parent: '/architecture-cities/',
  },
  '/henderson/': {
    href: '/coast-to-coast/henderson/',
    name: 'Henderson Architecture',
    parent: '/architecture-cities/',
  },
  '/hinsdale/': {
    href: '/coast-to-coast/hinsdale/',
    name: 'Hinsdale Architecture',
    parent: '/architecture-cities/',
  },
  '/lake-tahoe/': {
    href: '/coast-to-coast/lake-tahoe/',
    name: 'Lake Tahoe Architecture',
    parent: '/architecture-cities/',
  },
  '/las-vegas/': {
    href: '/coast-to-coast/las-vegas/',
    name: 'Las Vegas Architecture',
    parent: '/architecture-cities/',
  },
  '/los-angeles/': {
    href: '/coast-to-coast/los-angeles/',
    name: 'Los Angeles Architecture',
    parent: '/architecture-cities/',
  },
  '/memphis/': {
    href: '/coast-to-coast/memphis/',
    name: 'Memphis Architecture',
    parent: '/architecture-cities/',
  },
  '/monterey/': {
    href: '/coast-to-coast/monterey/',
    name: 'Monterey Architecture',
    parent: '/architecture-cities/',
  },
  '/napa-valley/': {
    href: '/coast-to-coast/napa-valley/',
    name: 'Napa Valley Architecture',
    parent: '/architecture-cities/',
  },
  '/natchez/': {
    href: '/coast-to-coast/natchez/',
    name: 'Natchez Architecture',
    parent: '/architecture-cities/',
  },
  '/new-orleans/': {
    href: '/coast-to-coast/new-orleans/',
    name: 'New Orleans Architecture',
    parent: '/architecture-cities/',
  },
  '/new-york-city/': {
    href: '/coast-to-coast/new-york/',
    name: 'New York Architecture',
    parent: '/architecture-cities/',
  },
  '/northfield/': {
    href: '/coast-to-coast/northfield/',
    name: 'Northfield Architecture',
    parent: '/architecture-cities/',
  },
  '/palm-beach/': {
    href: '/coast-to-coast/palm-beach/',
    name: 'Palm Beach Architecture',
    parent: '/architecture-cities/',
  },
  '/pasadena/': {
    href: '/coast-to-coast/pasadena/',
    name: 'Pasadena Architecture',
    parent: '/architecture-cities/',
  },
  '/pittsburgh/': {
    href: '/coast-to-coast/pittsburgh/',
    name: 'Pittsburgh Architecture',
    parent: '/architecture-cities/',
  },
  '/raleigh/': {
    href: '/coast-to-coast/raleigh/',
    name: 'Raleigh Architecture',
    parent: '/architecture-cities/',
  },
  '/salem/': {
    href: '/coast-to-coast/salem/',
    name: 'Salem Architecture',
    parent: '/architecture-cities/',
  },
  '/san-antonio/': {
    href: '/coast-to-coast/san-antonio/',
    name: 'San Antonio Architecture',
    parent: '/architecture-cities/',
  },
  '/san-diego/': {
    href: '/coast-to-coast/san-diego/',
    name: 'San Diego Architecture',
    parent: '/architecture-cities/',
  },
  '/san-francisco/': {
    href: '/coast-to-coast/san-francisco/',
    name: 'San Francisco Architecture',
    parent: '/architecture-cities/',
  },
  '/santa-barbara/': {
    href: '/coast-to-coast/santa-barbara/',
    name: 'Santa Barbara Architecture',
    parent: '/architecture-cities/',
  },
  '/santa-fe/': {
    href: '/coast-to-coast/santa-fe/',
    name: 'Santa Fe Architecture',
    parent: '/architecture-cities/',
  },
  '/santa-monica/': {
    href: '/coast-to-coast/santa-monica/',
    name: 'Santa Monica Architecture',
    parent: '/architecture-cities/',
  },
  '/sarasota/': {
    href: '/coast-to-coast/sarasota/',
    name: 'Sarasota Architecture',
    parent: '/architecture-cities/',
  },
  '/seattle/': {
    href: '/coast-to-coast/seattle/',
    name: 'Seattle Architecture',
    parent: '/architecture-cities/',
  },
  '/stamford/': {
    href: '/coast-to-coast/stamford/',
    name: 'Stamford Architecture',
    parent: '/architecture-cities/',
  },
  '/telluride/': {
    href: '/coast-to-coast/telluride/',
    name: 'Telluride Architecture',
    parent: '/architecture-cities/',
  },
  '/tucson/': {
    href: '/coast-to-coast/tucson/',
    name: 'Tucson Architecture',
    parent: '/architecture-cities/',
  },
  '/vancouver/': {
    href: '/coast-to-coast/vancouver/',
    name: 'Vancouver Architecture',
    parent: '/architecture-cities/',
  },
  '/venice/': {
    href: '/coast-to-coast/venice/',
    name: 'Venice Architecture',
    parent: '/architecture-cities/',
  },
  '/coastal/': {
    href: '/coast-to-coast/coastal/',
    name: 'Coastal Architecture',
    parent: '/architecture-regional/',
  },
  '/gulf-coast/': {
    href: '/coast-to-coast/gulf-coast/',
    name: 'Gulf Coast Architecture',
    parent: '/architecture-regional/',
  },
  '/mountain-estate/': {
    href: '/coast-to-coast/mountain-estate/',
    name: 'Mountain Estate Architecture',
    parent: '/architecture-regional/',
  },
  '/potomac-valley-architecture/': {
    href: '/coast-to-coast/potomac-valley/',
    name: 'Potomac Valley Architecture',
    parent: '/architecture-regional/',
  },
  '/texas-properties/': {
    href: '/coast-to-coast/texas-regional/',
    name: 'Texas Properties Architecture',
    parent: '/architecture-regional/',
  },
  '/canada/': {
    href: '/coast-to-coast/canada/',
    name: 'Canada Architecture',
    parent: '/architecture-international/',
  },
  '/france/': {
    href: '/coast-to-coast/france/',
    name: 'France Architecture',
    parent: '/architecture-international/',
  },
  '/hungary/': {
    href: '/coast-to-coast/hungary/',
    name: 'Hungary Architecture',
    parent: '/architecture-international/',
  },
  '/italy/': {
    href: '/coast-to-coast/italy/',
    name: 'Italy Architecture',
    parent: '/architecture-international/',
  },
  '/portugal/': {
    href: '/coast-to-coast/portugal/',
    name: 'Portugal Architecture',
    parent: '/architecture-international/',
  },
  '/vietnam/': {
    href: '/coast-to-coast/vietnam/',
    name: 'Vietnam Architecture',
    parent: '/architecture-international/',
  },
};
